<script type="text/javascript">
    new ITwebexperts_Rentalbundles_Country_Selector({
        countrySelectorClass: 'dd.rentalbundles select',
        blockSelector: 'dd.rentalbundles',
        startDateSelector: 'div.dateSelectorStart input',
        bundleDateInputsSelector: 'dd.rentalbundledates input'
    });
</script>


<?php /* @var $this Mage_Bundle_Block_Catalog_Product_View_Type_Bundle_Option_Select */ ?>
<?php $_option      = $this->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $this->_getDefaultValues(); ?>
<?php $tierPriceHtml = ''; ?>

<dd class="rentalbundledates">
    <div class="input-box">
        <div class="datesSelector">
            <div class="dateStartLine">
                <div class="dateSelectorStart">
                    <label for="bundle_start_date"><?php echo $this->__('Requested Delivery Date'); ?></label>
                    <input type="text" id="bundle_start_date" name="start_date" class="validate-date  required-entry" />
                </div>
            </div>
            <div class="dateEndLine">
                <div class="dateSelectorEnd">
                    <label for="bundle_end_date"><?php echo $this->__('Trip Return Date'); ?></label>
                    <input type="text" id="bundle_end_date" name="end_date" class="validate-date required-entry" />
                </div>
            </div>
        </div>
    </div>
</dd>

<dt>
    <label<?php if ($_option->getRequired()) echo ' class="required"' ?>><?php echo $this->escapeHtml($_option->getTitle()) ?><?php if ($_option->getRequired()) echo '<em>*</em>' ?></label>
</dt>
    <?php
    $i = 0;
    foreach ($_selections as $_selection) {
        $i++;
        ?>
<dd class="rentalbundles" <?php echo 1 < $i ? 'style="display:none;"' : '' ?>>
    <div class="input-box">
        <?php /** @var $_selection Mage_Catalog_Model_Product*/ ?>
        <?php if ($this->_showSingle()): ?>
            <?php echo $this->getSelectionTitlePrice($_selections[0]); ?>
            <?php if ($_selections[0]->getSelectionCanChangeQty()): ?>
                <?php $tierPriceHtml = $this->getTierPriceHtml($_selections[0]); ?>
            <?php endif; ?>
            <input type="hidden" name="bundle_option[<?php echo $_option->getId() ?>]" value="<?php echo $_selections[0]->getSelectionId() ?>"/>
        <?php else:?>

            <select onchange="bundle.changeSelection(this)" name="bundle_option[<?php echo $_option->getId() ?>][]" class="bundle-option-<?php echo $_option->getId() ?><?php if (2 > $i) echo ' required-entry' ?> bundle-option-select change-container-classname">
                <option value=""><?php echo $this->__('Choose a selection...') ?></option>
                <?php foreach ($_selections as $_selection): ?>
                    <?php if ($_selection->getSelectionCanChangeQty() && $this->_isSelected($_selection)): ?>
                        <?php $tierPriceHtml = $this->getTierPriceHtml($_selection); ?>
                    <?php endif; ?>
                    <option value="<?php echo $_selection->getSelectionId() ?>"<?php if ($this->_isSelected($_selection)) echo ' selected="selected"' ?><?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>><?php echo $this->getSelectionTitlePrice($_selection, false) ?></option>
                <?php endforeach; ?>
            </select>

            <div class="datesSelector">
                <div class="dateStartLine">
                    <div class="dateSelectorStart">
                        <label for="readStartDate<?php echo $i; ?>"><?php echo $this->__('Arrival Date'); ?></label>
                        <input type="text" id="readStartDate<?php echo $i; ?>" name="country_start_date[]" class="validate-date <?php if (2 > $i) echo ' required-entry' ?>"/>
                    </div>
                </div>
            </div>

        <?php endif; ?>
    </div>
    <span id="bundle-option-<?php echo $_option->getId() ?>-tier-prices"> <?php echo $tierPriceHtml; ?></span>
    <!--span class="qty-holder">
        <label for="bundle-option-<?php echo $_option->getId() ?>-qty-input"><?php echo $this->__('Qty:') ?>&nbsp;</label><input onkeyup="bundle.changeOptionQty(this, event)" onblur="bundle.changeOptionQty(this, event)" <?php if (!$_canChangeQty) echo ' disabled="disabled"' ?> id="bundle-option-<?php echo $_option->getId() ?>-qty-input" class="input-text qty<?php if (!$_canChangeQty) echo ' qty-disabled' ?>" type="text" name="bundle_option_qty[<?php echo $_option->getId() ?>]" value="<?php echo $_defaultQty ?>"/>
    </span-->
</dd>
    <?php
    }
    ?>