<?php /* @var $this ITwebexperts_Rentalbundles_Block_Adminhtml_Bundle_Catalog_Product_Composite_Fieldset_Options_Type_Multi */ ?>
<?php $_option = $this->getOption(); ?>
<?php $_selections = $_option->getSelections(); ?>
<?php $_skipSaleableCheck = Mage::helper('catalog/product')->getSkipSaleableCheck(); ?>
<dt>
    <label for="bundle-option-<?php echo $_option->getId() ?>"<?php if ($_option->getRequired()) echo ' class="required"' ?>><?php if ($_option->getRequired()) echo '<em>*</em>' ?><?php echo $this->escapeHtml($_option->getTitle()) ?></label>
</dt>
<dd class="rentalbundles-sim<?php if ($_option->decoratedIsLast) { ?> last<?php } ?>">
    <div class="input-box">
        <?php if (count($_selections) == 1 && $_option->getRequired()): ?>
            <?php echo $this->getSelectionQtyTitlePrice($_selections[0]) ?>
            <input type="hidden" name="bundle_option[<?php echo $_option->getId() ?>]" value="<?php echo $_selections[0]->getSelectionId() ?>" price="<?php echo $this->getSelectionPrice($_selections[0]) ?>"/>
        <?php else: ?>
            <select multiple="multiple" size="5" id="bundle-option-<?php echo $_option->getId() ?>" name="bundle_option[<?php echo $_option->getId() ?>][]" class="bundle-option-<?php echo $_option->getId() ?><?php if ($_option->getRequired()) echo ' required-entry' ?> bundle-option-select multiselect change-container-classname" onchange="ProductConfigure.bundleControl.changeSelection(this)">
                <?php if (!$_option->getRequired()): ?>
                    <option value=""><?php echo $this->__('None') ?></option>
                <?php endif; ?>
                <?php foreach ($_selections as $_selection): ?>
                    <option value="<?php echo $_selection->getSelectionId() ?>"<?php if ($this->_isSelected($_selection)) echo ' selected="selected"' ?><?php if (!$_selection->isSaleable() && !$_skipSaleableCheck) echo ' disabled="disabled"' ?> price="<?php echo $this->getSelectionPrice($_selection) ?>"><?php echo $this->getSelectionQtyTitlePrice($_selection, false) ?></option>
                <?php endforeach; ?>
            </select>
        <?php endif; ?>
    </div>
</dd>